/**
 * \file CityReport.h
 *
 * \author Charles B. Owen
 *
 * The city report is generated by the members of the city.
 * It is a collection of objects of type CMemberReport.
 */

#pragma once

#include <memory>
#include <vector>
#include <list>

class CCity;
class CMemberReport;

/**
 * The city report is generated by the members of the city.
 * It is a collection of objects of type CMemberReport.
*/
class CCityReport
{
protected:
    /**
     * A bin holds some number of member reports
     */
    class Bin {
    public:
        /// A vector of reports stored in this Bin
        std::vector < std::shared_ptr<CMemberReport>> mReports;
    };

    /// The list of Bin objects holding report data.
    std::list<Bin> mBins;

public:
    CCityReport(CCity* city);

    void Add(std::shared_ptr<CMemberReport> report);

    /** Iterator that iterates over the city tiles */
    class Iter
    {
    public:
        /** Constructor
         * \param city The city we are iterating over */
        Iter(CCityReport* cityReport, int pos, std::list<CCityReport::Bin>::iterator binPosition) 
            : mCityReport(cityReport), mPos(pos), mBinPosition(binPosition) {}

        /** Test for end of the iterator
         * \returns True if we this position equals not equal to the other position */
        bool operator!=(const Iter& other) const
        {
            return mPos != other.mPos || mBinPosition != other.mBinPosition;
        }

        /** Get value at current position
         * \returns Value at mPos in the collection */
        std::shared_ptr<CMemberReport> operator *() const { return mBinPosition->mReports[mPos]; }

        /** Increment the iterator
         * \returns Reference to this iterator */
        const Iter& operator++()
        {
            mPos++;
            if (mPos >= mBinPosition->mReports.size())
            {
                mBinPosition++;
                mPos = 0;
            }
            return *this;
        }

    private:
        CCityReport* mCityReport;   ///< City we are iterating over
        int mPos;       ///< Position in the collection
        std::list<CCityReport::Bin>::iterator mBinPosition;
    };

    /** Get an iterator for the beginning of the collection
    * \returns Iter object at position 0 */
    Iter begin() { return Iter(this, 0, mBins.begin()); }

    /** Get an iterator for the end of the collection
     * \returns Iter object at position past the end */
    Iter end() { return Iter(this, 0, mBins.end()); }

private:
    /// The city this report is for
    CCity* mCity;
};

